### PR TITLE
Correct seek to last granule of packet

### LINKED ISSUE #19: "Ran out of packets?!" when seeking
The new 0.10.3 release appears to have a bug that causes an `InvalidDataException` to be thrown with the message "Ran out of packets?!" when seeking/setting the sample position. This appears to be a regression in 0.10.3; it did not happen for me in 0.10.2.

Here is a small sample program that easily reproduces the issue for me:

```
using NVorbis;

namespace NVorbisTest
{
    class Program
    {
        static void Main()
        {
            VorbisReader reader = new("test.ogg");
            while (reader.SamplePosition < reader.TotalSamples)
                reader.SamplePosition += reader.Channels;
        }
    }
}
```

I have been able to reproduce this easily with every ogg file I've tried, but just in case here is a [test.ogg](https://github.com/NVorbis/NVorbis/files/6411889/test.ogg.zip) file that I know reproduces this issue consistently for me.

For convenience, here is the stack trace:

```
System.IO.InvalidDataException: Ran out of packets?!
   at NVorbis.Ogg.PacketProvider.FindPacket(Int32 pageIndex, Int64& granulePos, GetPacketGranuleCount getPacketGranuleCount, Boolean isRecursed)
   at NVorbis.Ogg.PacketProvider.SeekTo(Int64 granulePos, Int32 preRoll, GetPacketGranuleCount getPacketGranuleCount)
   at NVorbis.StreamDecoder.SeekTo(Int64 samplePosition, SeekOrigin seekOrigin)
   at NVorbis.StreamDecoder.set_SamplePosition(Int64 value)
   at NVorbis.VorbisReader.set_SamplePosition(Int64 value)
   at NVorbisTest.Program.Main() in C:\Users\walt\Desktop\NVorbisTest\Program.cs:line 11
```

### LINKED ISSUE #20: Granule Position was -1 but page does not have exactly 1 continued packet.
Some files fail with the error in the title when creating a VorbisReader.

[Here's one such file.](https://drive.google.com/file/d/1G81eHWST1LdjM5zFaN2MsREk-0CGkzP1/view?usp=sharing)

The file works in other programs like Audacity and can also be opened with v0.9.1

### PR DESCRIPTION
**Pull request by ioctlLR**
Correct seek to sample in first 2 data packets.

Closes #19, #22, and #23.

@waltdestler  can you give this a shot?

### CODE REVIEW

**Comment by waltdestler** [comment]
Some things are fixed and some aren't. Commented on the original issues with more info.

**Comment by ioctlLR** [comment]
@waltdestler please give this a try again.  It "should" fix everything.

**Comment by waltdestler** [comment]
Everything seems good on my end. All my tests are passing with flying colors. Great work!

I did notice something that I think **I** actually broke with my previous PR, which is that it is no longer possible to seek to the sample index one past the last sample (i.e. `reader.SamplePosition = reader.TotalSamples;` now throws an exception), which used to be possible and IMHO should be fixed. I'm just not sure what the best way to fix it is.

**Comment by waltdestler** [comment]
Oh, actually, I think I got myself confused by forgetting that I needed to divide TotalSamples by the number of channels. (Right?) Though I remain confused about why I can, for a 2-channel file, set SamplePosition to a value > TotalSamples/2, and what I should expect to happen by doing that.

**Comment by ioctlLR** [comment]
Seeking to TotalSamples should now work as expected.  I'll probably merge in the morning and get ready to do a release.

**Comment by waltdestler** [comment]
Everything's working for me! I ran the latest code through a battery of seek tests with a handful of different files and everything seems to be working perfectly. Great works! Thanks so much for the time you've put into this these past few days, much appreciated!

**Pull request merged**
